package BookAPitch::Model::BookAPitchDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

my $dsn = $ENV{APP_DB} ||= 'dbi:Pg:dbname=bookapitchdb';
warn "IN HERE ";
__PACKAGE__->config(
    schema_class => 'BookAPitch::Schema',

    connect_info => {
        dsn => $dsn,
        user => 'bookapitchuser',
        password => 'Wednesday730',
        AutoCommit => q{1},
    }
);

=head1 NAME

BookAPitch::Model::BookAPitchDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<BookAPitch>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<BookAPitch::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.63

=head1 AUTHOR

Minesh Patel

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
